/*

 BIRD.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char BirdGraphisc[] =
{
  0x7E,0x7E,0x81,0x81,0x01,0x07,0xA2,0xA7,
  0x4F,0x40,0x0F,0x00,0x81,0x81,0x7E,0x7E
};

/* End of BIRD.C */
