/*

 BG_TILEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 9
   Tile set      : Z:\home\brod8362\projects\gbflappy\tilemap\background.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundTilemapWidth 9
#define BackgroundTilemapHeight 9
#define BackgroundTilemapBank 0

unsigned char BackgroundTilemap[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x05,0x00,0x00,0x00,0x00,0x00,0x44,0x00,0x00,
  0x00,0x00,0x00
};

/* End of BG_TILEMAP.C */
