/*

 GRAPHICS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 4

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BackgroundGraphicsBank 0

/* Super Gameboy palette 0 */
#define BackgroundGraphicsSGBPal0c0 6076
#define BackgroundGraphicsSGBPal0c1 8935
#define BackgroundGraphicsSGBPal0c2 6596
#define BackgroundGraphicsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BackgroundGraphicsSGBPal1c0 6076
#define BackgroundGraphicsSGBPal1c1 8935
#define BackgroundGraphicsSGBPal1c2 6596
#define BackgroundGraphicsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BackgroundGraphicsSGBPal2c0 6076
#define BackgroundGraphicsSGBPal2c1 8935
#define BackgroundGraphicsSGBPal2c2 6596
#define BackgroundGraphicsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BackgroundGraphicsSGBPal3c0 6076
#define BackgroundGraphicsSGBPal3c1 8935
#define BackgroundGraphicsSGBPal3c2 6596
#define BackgroundGraphicsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BackgroundGraphicsCGBPal0c0 6076
#define BackgroundGraphicsCGBPal0c1 276
#define BackgroundGraphicsCGBPal0c2 32767
#define BackgroundGraphicsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define BackgroundGraphicsCGBPal1c0 29344
#define BackgroundGraphicsCGBPal1c1 32767
#define BackgroundGraphicsCGBPal1c2 31288
#define BackgroundGraphicsCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define BackgroundGraphicsCGBPal2c0 29344
#define BackgroundGraphicsCGBPal2c1 32767
#define BackgroundGraphicsCGBPal2c2 31288
#define BackgroundGraphicsCGBPal2c3 0

/* Gameboy Color palette 3 */
#define BackgroundGraphicsCGBPal3c0 6076
#define BackgroundGraphicsCGBPal3c1 8935
#define BackgroundGraphicsCGBPal3c2 6596
#define BackgroundGraphicsCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BackgroundGraphicsCGBPal4c0 6076
#define BackgroundGraphicsCGBPal4c1 8935
#define BackgroundGraphicsCGBPal4c2 6596
#define BackgroundGraphicsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BackgroundGraphicsCGBPal5c0 6076
#define BackgroundGraphicsCGBPal5c1 8935
#define BackgroundGraphicsCGBPal5c2 6596
#define BackgroundGraphicsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BackgroundGraphicsCGBPal6c0 6076
#define BackgroundGraphicsCGBPal6c1 8935
#define BackgroundGraphicsCGBPal6c2 6596
#define BackgroundGraphicsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BackgroundGraphicsCGBPal7c0 6076
#define BackgroundGraphicsCGBPal7c1 8935
#define BackgroundGraphicsCGBPal7c2 6596
#define BackgroundGraphicsCGBPal7c3 5344

/* SGB palette entries. */
#define BackgroundGraphicsSGB0 0
#define BackgroundGraphicsSGB1 0
#define BackgroundGraphicsSGB2 0
#define BackgroundGraphicsSGB3 0
#define BackgroundGraphicsSGB4 0

/* CGB palette entries. */
#define BackgroundGraphicsCGB0 1
#define BackgroundGraphicsCGB1 1
#define BackgroundGraphicsCGB2 1
#define BackgroundGraphicsCGB3 1
#define BackgroundGraphicsCGB4 2
/* Start of tile array. */
extern unsigned char BackgroundGraphics[];

/* End of GRAPHICS.H */
